=== LaurenRolan/XML/TP2/pt2/biblio.dtd
<!ELEMENT biblio (livre*, article*)*>

<!ELEMENT livre (titre,auteur,tomes,infosEdition, avis?)>
<!ELEMENT article (titre,auteur,infosPublication, avis?)>

<!ELEMENT titre (#PCDATA)>
<!ATTLIST titre sousTitre CDATA #IMPLIED>

<!ELEMENT auteur (#PCDATA)>
<!ELEMENT tomes EMPTY>
<!ATTLIST tomes nombrePage CDATA #REQUIRED>
<!ATTLIST tomes sousTitre CDATA #IMPLIED>

<!ELEMENT avis (#PCDATA)>
<!ELEMENT infosEdition (editeur, lieuEdition, lieuImpression, ISBN)>
<!ELEMENT editeur (#PCDATA)>
<!ELEMENT lieuEdition (#PCDATA)>
<!ELEMENT lieuImpression (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>

<!ELEMENT infosPublication (pages, anneePublication, numeroJournal)>
<!ATTLIST infosPublication nomJournal CDATA "Feuille de Chou">
<!ELEMENT pages (#PCDATA)>
<!ELEMENT anneePublication (#PCDATA)>
<!ELEMENT numeroJournal (#PCDATA)>

=== LaurenRolan/XML/TP2/pt2/biblio.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE biblio SYSTEM "biblio.dtd">
<biblio>
<livre>
	<titre> Test 1 </titre>
	<auteur>Auteur 1</auteur>
	<tomes nombrePage='3'></tomes>
	<infosEdition>
		<editeur>Lauren</editeur>
		<lieuEdition>Porto Alegre</lieuEdition>
		<lieuImpression>Porto Alegre</lieuImpression>
		<ISBN> 12345678</ISBN>
	</infosEdition>
	<avis>Cet un bon livre.</avis>
</livre>

<article>
	<titre> Test 2 </titre>
	<auteur>Auteur 2</auteur>
	<infosPublication>
		<pages>5</pages>
		<anneePublication>2017</anneePublication>
		<numeroJournal>123</numeroJournal>
	</infosPublication>
	<avis>Cet un bon article.</avis>
</article>
</biblio>
