=== LaurenRolan/XML/TP2/pt1/biblio.dtd
<!ELEMENT biblio (livre*, article*)*>

<!ELEMENT livre (titre,auteur,tomes,infosEdition, avis?)>
<!ELEMENT article (titre,auteur,infosPublication, avis?)>

<!ELEMENT titre (#PCDATA)>
<!ELEMENT auteur (#PCDATA)>
<!ELEMENT tomes (#PCDATA)>
<!ELEMENT avis (#PCDATA)>
<!ELEMENT infosEdition (editeur, lieuEdition, lieuImpression, ISBN)>
<!ELEMENT editeur (#PCDATA)>
<!ELEMENT lieuEdition (#PCDATA)>
<!ELEMENT lieuImpression (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>

<!ELEMENT infosPublication (nomJournal, pages, anneePublication, numeroJournal)>
<!ELEMENT nomJournal (#PCDATA)>
<!ELEMENT pages (#PCDATA)>
<!ELEMENT anneePublication (#PCDATA)>
<!ELEMENT numeroJournal (#PCDATA)>

=== LaurenRolan/XML/TP2/pt1/biblio.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE biblio SYSTEM "biblio.dtd">
<biblio>
<livre>
	<titre>Test 1</titre>
	<auteur>Auteur 1</auteur>
	<tomes>3</tomes>
	<infosEdition>
		<editeur>Lauren</editeur>
		<lieuEdition>Porto Alegre</lieuEdition>
		<lieuImpression>Porto Alegre</lieuImpression>
		<ISBN> 12345678</ISBN>
	</infosEdition>
	<avis>Cet un bon livre.</avis>
</livre>
</biblio>
