=== LaurenRolan/XML/TP2/pt4/biblio.xsd
<?xml version='1.0' encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="biblio" type="bibliographie"/>

<xs:complexType name='bibliographie'>
	<xs:choice maxOccurs="unbounded">
		<xs:element name="livre" type="livre" maxOccurs="unbounded"/>
		<xs:element name="article" type="article" maxOccurs="unbounded" />
	</xs:choice>
</xs:complexType>

<xs:complexType name='livre'>
	<xs:sequence>
		<xs:element name="titre" type="xs:string" />
		<xs:element name="auteur" type="xs:string" />

		<xs:element name="tomes">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
			<xs:element name="tome"  maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name='nombrePage' type='xs:nonNegativeInteger' use='required' />
					<xs:attribute name='sousTitre' type='xs:string'/>
				</xs:complexType>
			</xs:element>
			</xs:choice>
		</xs:complexType>
		</xs:element>
		<xs:element name="infosEdition">
		<xs:complexType>
			<xs:sequence>
			<xs:element name='editeur' type='xs:string' />
			<xs:element name='lieuEdition' type='xs:string' />
			<xs:element name='lieuImpression' type='xs:string' /> 
			<xs:element name='ISBN' type='xs:string' />
			</xs:sequence>
		</xs:complexType>
		</xs:element>
		<xs:element name="avis" type="xs:string" />
	</xs:sequence>
</xs:complexType>

<xs:simpleType name='typeISBN'>
	<xs:restriction base='xs:string'> 
		<xs:length value='10'> </xs:length>
	</xs:restriction>
</xs:simpleType>

<xs:complexType name='article'>
	<xs:sequence>
		<xs:element name="titre" type="xs:string" />
		<xs:element name="auteur" type="xs:string" />
		<xs:element name="infosPublication">
		<xs:complexType>
			<xs:sequence>
			<xs:element name='pages' type='typePage' />
			<xs:element name='anneePublication' type='xs:gYear' />
			<xs:element name='numeroJournal' type='xs:nonNegativeInteger' /> 
			</xs:sequence>
			<xs:attribute name='nomJournal' type='xs:string' default='Feuille de Chou'/>
		</xs:complexType>
		</xs:element>
		<xs:element name="avis" type="xs:string" />
	</xs:sequence>
</xs:complexType>

<xs:simpleType name='typePage'>
	<xs:restriction base='xs:string'>
		<xs:whiteSpace value="preserve"/>
		<xs:pattern value='[0-9]*\sÃ \s[0-9]*'> </xs:pattern>
	</xs:restriction>
</xs:simpleType>
</xs:schema>

=== LaurenRolan/XML/TP2/pt4/biblio.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<biblio xsi:noNamespaceSchemaLocation="biblio.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

<livre>
	<titre> Test 1 </titre>
	<auteur>Auteur 1</auteur>
	<tomes><tome nombrePage='3'></tome></tomes>
	<infosEdition>
		<editeur>Lauren</editeur>
		<lieuEdition>Porto Alegre</lieuEdition>
		<lieuImpression>Porto Alegre</lieuImpression>
		<ISBN> 12345678910</ISBN>
	</infosEdition>
	<avis>Cet un bon livre.</avis>
</livre>

<article>
	<titre> Test 2 </titre>
	<auteur>Auteur 2</auteur>
	<infosPublication>
		<pages>5 Ã  15</pages>
		<anneePublication>2017</anneePublication>
		<numeroJournal>123</numeroJournal>
	</infosPublication>
	<avis>Cet un bon article.</avis>
</article>
</biblio>
